### ISSUE TITLE
Upload to TER & Packagist

### ISSUE THREAD

**Issue by mikestreety** [neuedaten/global_password#5]
Hey @r12r - I have released v2.0.0.

Is it possible to get this uploaded to the TER & [Packagist](https://packagist.org/packages/neuedaten/global-password) please?

Thanks

**Comment by r12r** [comment]
@mikestreety 
really cool! Thanks for your effort!
I will soon make a release for the TER.

**Comment by r12r** [comment]
Hi @mikestreety,

I have tested your extension. really cool! Especially the variants are very helpful!

In one of my environments I got a PHP warning. I modified the code a little bit. Is in the master branch.
Can you please pull that once and test if it still works for you?

After that I will finish the version for TER.

Have you by chance already tested it with LTS 12? Otherwise I have to take care of it soon.

**Comment by mikestreety** [comment]
Ah perfect, that looks fine :) thanks for catching that.

No, i've not tested with 12 as we don't currently have any 12 sites setup.

**Comment by r12r** [comment]
@mikestreety 
Done. Have a nice evening!
